name: CI/CD

on:
  push:
    branches:
      - test

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: fastapiacrtest.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    - name: Build and push Docker image
      run: |
        docker build . -t fastapiacrtest.azurecr.io/fastapi-app:${{ github.sha }}
        docker push fastapiacrtest.azurecr.io/fastapi-app:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Helm
      run: |
        curl https://baltocdn.com/helm/signing.asc | sudo apt-key add -
        sudo apt-get install apt-transport-https --yes
        echo "deb https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
        sudo apt-get update
        sudo apt-get install helm
    - name: Set up Kubeconfig
      uses: azure/aks-set-context@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        cluster-name: yourClusterName
        resource-group: yourResourceGroupName
    - name: Deploy to AKS
      run: |
        helm upgrade --install fastapi-app ./charts/fastapi-app --set image.tag=${{ github.sha }}
