name: CI/CD

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  build-and-push:
    runs-on: 
        - mac-os
        - self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build Docker image
      run: |
         docker build . -t ${{ secrets.ACR_SERVER }}/fastapi-app:${{ github.sha }}
    
    - name: Run Docker Image
      run: docker run -d -p 8000:8000 --name api-app ${{ secrets.ACR_SERVER }}/fastapi-app:${{ github.sha }}

    - name: Wait for API to start
      uses: jakejarvis/wait-action@master
      with:
        time: 15s

    - name: Check FastAPI health
      run: curl http://localhost:8000/health

    - name: Stop Docker container
      run: docker stop api-app
      

    - name: push Docker image
      run: |
         docker push ${{ secrets.ACR_SERVER }}/fastapi-app:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: mac-os
    steps:
    - uses: actions/checkout@v2
    - name: Install Helm
      run: |
        curl https://baltocdn.com/helm/signing.asc | sudo apt-key add -
        sudo apt-get install apt-transport-https --yes
        echo "deb https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
        sudo apt-get update
        sudo apt-get install helm
        
    - name: Login to Azure CLI
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.ARM_CLIENT_ID }}
        tenant-id: ${{ secrets.ARM_TENANT_ID }}
        subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  
    - name: Set up Kubeconfig
      run: |
        az aks get-credentials --name fast-api --resource-group terraform-test --overwrite-existing
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

    - name: Create Image Pull Secret
      run: |
        kubectl create secret docker-registry acr-secret \
          --docker-server=${{ secrets.ACR_SERVER }} \
          --docker-username=${{ secrets.ACR_USERNAME }} \
          --docker-password=${{ secrets.ACR_PASSWORD }} \
          --namespace=default \
          --dry-run=client -o yaml | kubectl apply -f -
        
    - name: Deploy to AKS
      run: |
        helm upgrade --install fastapi-app ./charts/fastapi-app --set image.tag=${{ github.sha }} --set image.pullSecrets[0].name=acr-secret
